apiVersion: v1 #kubernetes api version
kind: Pod
metadata:

  name: webapp  #application name
  labels:
    app: webapp
    release: "0"

spec:
  containers:
  - name: webapp  #container name
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0  # docker image url (bkz. dockerHub)

---
apiVersion: v1 #kubernetes api version
kind: Pod
metadata:
  name: webapp-release-0-5
  labels:
    app: webapp
    release: "0-5"
spec:
  containers:
  - name: webapp
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

